# _quarto.yml
my_global_folders:
    USER_OUTPUT_FOLDER: "../zzz_zzz_USER_OUPUT_FOLDER"
    png_folder: "zzz_output_report02_R_png_folder"

list_input_file_path:
    str_file_path_RData: "../zzz_zzz_USER_OUPUT_FOLDER/zzz_output_report01_RQuarto_00_Env.RData"




project:
  type: default
  pre-render:
    - "Rscript script_R_01_pre_render.R"
  post-render:
    - "Rscript script_R_02_post_render.R"
  render:
    - "*.qmd"
    - "!drafts/*"
  preview:
    port: 8888
    browser: false
  # Variables que usarán los scripts

format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    output-file: "zzz_output_report03_pdf_00.pdf"
    theme: cosmo
    css:
      - ../common_files/custom_theme.css
    keep-tex: true

execute:
  enabled: true
  echo: true
  warning: true
  error: true
  message: true
  include: true
  eval: true
  cache: false
  freeze: false
  debug: false







knitr:
  opts_chunk:
    collapse: false
    comment: ""
    dev: "svg"
    out.width: "100%"
    fig.align: "center"
    cache: false

metadata:
  lang: en
  author: "Rscience"
  date: today
