# _quarto.yml
# Local inputs
local_resources:
    pack01_no_config_run:
        description:  "ADD..."
        files:
            qmd_run:
                file_name: "report01_NO_CONFIG_gen_files_RUN.qmd"
                must_exists_init: true
                must_exists_pre: true
                is_input: true
                is_output: false
            html_run:
                file_name: "report01_NO_CONFIG_gen_files_RUN_HIDDEN.html"
                must_exists_init: false
                must_exists_pre: false
                is_input: false
                is_output: true
        folders: null
    pack02_config_run:
        description:  "ADD..."
        files:
            quarto_config:
                file_name: "_quarto.yml"
                must_exists_init: true
                must_exists_pre: true
                is_input: true
                is_output: false
            qmd_run:
                file_name: "report01_RQuarto_00_copy_PROD_RUN.qmd"
                must_exists_init: false
                must_exists_pre: true
                is_input: true
                is_output: false
            html_run:
                file_name: "zzz_output_report01_RQuarto_00_copy_PROD_RUN.html"
                must_exists_init: false
                must_exists_pre: true
                is_input: true
                is_output: false
            fn_local:
                file_name: "fn_local.R"
                must_exists_init: true
                must_exists_pre: true
                is_input: true
                is_output: false
            pre_script:
                file_name: &script_pre "script_R_01_pre_render.R"
                must_exists_init: true
                must_exists_pre: true
                is_input: true
                is_output: false
            post_script:
                file_name: &output_report01_file_name "script_R_02_post_render.R"
                must_exists_init: true
                must_exists_pre: true
                is_input: true
                is_output: false
    pack99_deep_clean:
        description: "ADD..."
        files:
            deep_clean:
                file_name: "_deep_clean.R"
                must_exists_init: true
                is_input: true
                is_output: false
            folders: null

# External inputs
external_inputs:
    file_paths:
        str_file_path_qmd:        "../lab03_prod/report00_RQuarto_00_original_PROD.qmd"
        str_file_path_appendix01: "../lab03_prod/report00_RQuarto_99_appendix01_sec13_Descriptive_RV.qmd"
        str_file_path_appendix02: "../lab03_prod/report00_RQuarto_99_appendix02_sec14_Descriptive_Residuals.qmd"
        str_file_path_appendix03: "../lab03_prod/report00_RQuarto_99_appendix03_sec15_to_17_ASA.qmd"

# Local Outputs
local_outputs:
    str_regex_inclusion_resources:  "^zzz_output_"
    str_regex_exclusion_resources:  "silenced"
    file_names:
        str_report01: "zzz_output_report01_RQuarto_00_copy_PROD_RUN.html"
        str_R_script_internal: "zzz_output_report01_R_script_internal.R"
        str_R_script_external: "zzz_output_report01_R_script_external.R"
        str_RQuarto_RData:     "zzz_output_report01_RQuarto_00_Env.RData"
        str_R_internal_RData:  "zzz_output_report01_R_internal_00_Env.RData"

# External Outputs
external_output:
    str_user_output_folder_path: "../zzz_zzz_output"

################################################################################
project:
  type: default
  pre-render:
    - "Rscript script_R_01_pre_render.R"
  post-render:
    - "Rscript script_R_02_post_render.R"
  render:
    - "report01_RQuarto_00_copy_PROD.qmd"
    # - "*.qmd"
    - "!drafts/*"
    - "!report01_NO_CONFIG_gen_files_RUN.qmd"
  preview:
    port: 8888
    browser: false
  # Variables que usarán los scripts

format:
  html:
    output-file: "zzz_output_report01_RQuarto_00_copy_PROD_RUN.html"
    theme: cosmo
    toc: true
    toc-float: true
    toc-location: right
    number-sections: true
    self-contained: true
    embed-resources: true
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1">
    fig-format: svg
    code-copy: true
    code-link: true
    grid:
      body-width: 2000px
      margin-width: 250px
      gutter-width: 1.5rem
  pdf:
    keep-tex: true

execute:
  enabled: true
  echo: true
  warning: true
  error: true
  message: true
  include: true
  eval: true
  cache: false
  freeze: false
  debug: false







knitr:
  opts_chunk:
    collapse: false
    comment: ""
    dev: "svg"
    out.width: "100%"
    fig.align: "center"
    cache: false

metadata:
  lang: en
  author: "Rscience"
  date: today
