# _quarto.yml
# Local inputs
local_inputs:
    list_local_input_files:
        quarto_config: "_quarto.yml"
        qmd_run:       "report99_html_Rscience.qmd"
        pre_script:    "script_R_01_pre_render.R"
        post_script:   "script_R_02_post_render.R"
        deep_clean:    "_deep_clean.R"
        list_local_input_folders: null
    str_regex_save_files: '.*\.Rproj$'

# External inputs
external_inputs:
    list_external_input_file_path:
        str_RData: "../zzz_zzz_output/zzz_output_report01_R_internal_00_Env.RData"

# Local Outputs
local_outputs:
    str_regex_inclusion_files:  "^zzz_output_"
    str_regex_exclusion_files:  "silenced"
    str_regex_inclusion_folders: "^zzz_output_"
    str_regex_exclusion_folders:  "silenced"
    str_R_script_internal: "zzz_output_report01_R_script_internal.R"
    str_R_script_external: "zzz_output_report01_R_script_external.R"

    
# External Outputs
external_output:
    str_user_output_folder_path: "../zzz_zzz_output"

################################################################################
project:
  type: default
  pre-render:
    - "Rscript script_R_01_pre_render.R"
  post-render:
    - "Rscript script_R_02_post_render.R"
  render:
    - "*.qmd"
    - "!drafts/*"
    - "!part00_header/**"
    - "!part01_init/**"
    - "!part02_theory/**"
  preview:
    port: 8888
    browser: false
  # Variables que usarán los scripts

format:
  html:
    output-file: "zzz_output_report99_html_Rscience_00.html"
    theme: cosmo
    css:
      - ../common_files/custom_theme.css
    toc: true
    toc-float: true
    toc-location: right
    number-sections: true
    self-contained: true
    embed-resources: true
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1">
    fig-format: svg
    code-copy: true
    code-link: true
    grid:
      body-width: 2000px
      margin-width: 250px
      gutter-width: 1.5rem


execute:
  enabled: true
  echo: true
  warning: true
  error: true
  message: true
  include: true
  eval: true
  cache: false
  freeze: false
  debug: false







knitr:
  opts_chunk:
    collapse: false
    comment: ""
    dev: "svg"
    out.width: "100%"
    fig.align: "center"
    cache: false

metadata:
  lang: en
  author: "Rscience"
  date: today
