# tools_config.yml
version: "1.0"
last_updated: "2024-01-15"
author: "Tu Nombre"

tools:

  Rs001_DESCRIPTIVE_1C:
    id: "desc_1c"
    name: "Descriptive - 1 Categorical"
    category: "Descriptive"
    cat_code: "descriptive"
    subcategory: "Univariate"
    description_short: "Frequency analysis for one categorical variable"
    description_long:  "Frequency analysis for one categorical variable"
    keywords: "cuantitative table descriptive"
    statistic_group: ["Descriptive"]
    folder_scripts:
      script001:
        folder_script: "Rs001_DESCRIPTIVE_1C_s001"
        special_module_file_path: "Rs001_DESCRIPTIVE_1C_s001/RShiny_modules.R"
        description_short: "El script 001 short DESCRIPTIVA."
        description_long: "El script 001 long  DESCRIPTIVA."
      script002:
        folder_script: "Rs001_DESCRIPTIVE_1C_s002"
        special_module_file_path: "Rs001_DESCRIPTIVE_1C_s002/RShiny_modules.R"
        description_short: "El script 002 short  DESCRIPTIVA."
        description_long: "El script 002 long  DESCRIPTIVA."

  Rs002_LM_QQ_FIX_ANOVA_01_1Way:
    id: "anova_1way"
    name: "Linear Model - Fixed Effects - Anova One Way"
    category: "Linear Model"
    cat_code: "general_linear_model"
    subcategory: "ANOVA"
    description_short: "Linear Model - One-way ANOVA with fixed effects"
    description_long:  "Linear Model - One-way ANOVA with fixed effects"
    keywords: "anova fixed effects one way glm"
    statistic_group: ["Linear Models"]
    folder_scripts:
      script001:
        folder_script: "Rs002_LM_QQ_FIX_ANOVA_01_1Way_s001"
        special_module_file_path: "Rs002_LM_QQ_FIX_ANOVA_01_1Way_s001/RShiny_modules.R"
        description_short: "El script 001 short ANOVA."
        description_long: "El script 001 long  ANOVA."
      script002:
        folder_script: "Rs002_LM_QQ_FIX_ANOVA_01_1Way_s002"
        special_module_file_path: "Rs002_LM_QQ_FIX_ANOVA_01_1Way_s002/RShiny_modules.R"
        description_short: "El script 002 short  ANOVA."
        description_long: "El script 002 long  ANOVA."






cat_code:
  descriptive:
    description: "Herramientas estadisticas asicoadias a...."
  general_linear_model:
    description: "Estimaciones polinomicas, pruebas de hipotesis y errores normales y homogeneos."
